global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-ssl'

receivers:
- name: 'team-ssl'
  slack_configs:
  - channel: '#ssl-alerts'
    send_resolved: true
  email_configs:
  - to: 'alerts@ssl-validator.com'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']